import type { Metadata } from "next";
import { ComponentType } from 'react';
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/app/components/Header";
import Footer from "@/app/components/Footer";
import { ReduxProvider } from "@/redux/provider";
// import { ErrorBoundary } from "react-error-boundary";
// import Error from "./components/Error";
import ErrorBoundary from "./components/ErrorBoundary";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My Courses",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="container mx-auto px-4 max-w-screen-xl my-2 ">
        {/* <ErrorBoundary fallback={<Error/>}> */}
        <ErrorBoundary>
        <ReduxProvider>
          <Header />
          {children}
          <Footer />
        </ReduxProvider>
        </ErrorBoundary>
        {/* </ErrorBoundary> */}
      </body>
    </html>
  );
}
